FROM python:3.11

WORKDIR /app

COPY requirements.txt /app

# Upgrade pip safely and install dependencies without threading
RUN python -m pip install --upgrade pip --progress-bar off && \
    pip install --no-cache-dir --progress-bar off -r requirements.txt

COPY . /app

CMD ["python", "app.py"]

